spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_practice
    username: ttasjwi
    password: db1004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
